CREATE TABLE "city"("__id" INTEGER PRIMARY KEY);
CREATE TABLE "person"("__id" INTEGER PRIMARY KEY);
ALTER TABLE "city" ADD "name" TEXT;
ALTER TABLE "person" ADD "name" TEXT;
ALTER TABLE "person" ADD "city" INTEGER REFERENCES "city";
ALTER TABLE "person" ADD "bio" BLOB;
INSERT INTO "city"("__id") VALUES(0);
UPDATE "city" SET "name" = X'5061726973' WHERE "__id" = 0;
INSERT INTO "city"("__id") VALUES(1);
UPDATE "city" SET "name" = X'4c696c6c65' WHERE "__id" = 1;
INSERT INTO "city"("__id") VALUES(14);
UPDATE "city" SET "name" = X'50c3a974616f7563686e6f6b' WHERE "__id" = 14;
INSERT INTO "person"("__id") VALUES(0);
UPDATE "person" SET "name" = X'52c3a96d69' WHERE "__id" = 0;
UPDATE "person" SET "city" = 1 WHERE "__id" = 0;
UPDATE "person" SET "bio" = X'54686973206973206d79206c696665' WHERE "__id" = 0;
INSERT INTO "person"("__id") VALUES(1);
UPDATE "person" SET "name" = X'4e6f7262657274' WHERE "__id" = 1;
UPDATE "person" SET "city" = 1 WHERE "__id" = 1;
UPDATE "person" SET "bio" = X'54686973206973206d79206c696665' WHERE "__id" = 1;
INSERT INTO "person"("__id") VALUES(2);
UPDATE "person" SET "name" = X'416c6578616e647265' WHERE "__id" = 2;
UPDATE "person" SET "city" = 14 WHERE "__id" = 2;
UPDATE "person" SET "bio" = X'54686973206973206d79206c696665' WHERE "__id" = 2;
DROP TABLE "city";
DROP TABLE "person";
CREATE TABLE "test"("__id" INTEGER PRIMARY KEY);
ALTER TABLE "test" ADD "a" INTEGER;
ALTER TABLE "test" ADD "b" BIGINT;
INSERT INTO "test"("__id") VALUES(0);
UPDATE "test" SET "a" = 1234 WHERE "__id" = 0;
UPDATE "test" SET "b" = 5678 WHERE "__id" = 0;
ALTER TABLE "test" ADD "d" TEXT;
ALTER TABLE "test" ADD "e" SMALLINT;
ALTER TABLE "test" DROP COLUMN "a";
INSERT INTO "test"("__id") VALUES(1);
UPDATE "test" SET "b" = 3 WHERE "__id" = 1;
UPDATE "test" SET "d" = X'34' WHERE "__id" = 1;
UPDATE "test" SET "e" = 0 WHERE "__id" = 1;
DELETE FROM "test" WHERE "__id" = 1;
UPDATE "test" SET "b" = 56789 WHERE "__id" = 0;
CREATE TABLE "ref"("__id" INTEGER PRIMARY KEY);
ALTER TABLE "ref" ADD "ref" INTEGER REFERENCES "test";
DROP TABLE "test";
DROP TABLE "ref";
CREATE TABLE "alltypes"("__id" INTEGER PRIMARY KEY);
ALTER TABLE "alltypes" ADD "s" TEXT;
ALTER TABLE "alltypes" ADD "i32" INTEGER;
ALTER TABLE "alltypes" ADD "i64" BIGINT;
ALTER TABLE "alltypes" ADD "ref" INTEGER REFERENCES "alltypes";
ALTER TABLE "alltypes" ADD "b" SMALLINT;
ALTER TABLE "alltypes" ADD "f" REAL;
ALTER TABLE "alltypes" ADD "d" REAL;
ALTER TABLE "alltypes" ADD "o" SMALLINT;
ALTER TABLE "alltypes" ADD "oulala" SMALLINT;
INSERT INTO "alltypes"("__id") VALUES(0);
UPDATE "alltypes" SET "s" = X'746f746f' WHERE "__id" = 0;
UPDATE "alltypes" SET "i32" = 123456789 WHERE "__id" = 0;
UPDATE "alltypes" SET "i64" = 123456789123456789 WHERE "__id" = 0;
UPDATE "alltypes" SET "ref" = 1 WHERE "__id" = 0;
UPDATE "alltypes" SET "b" = 1 WHERE "__id" = 0;
UPDATE "alltypes" SET "f" = 3.14 WHERE "__id" = 0;
UPDATE "alltypes" SET "d" = 3.14159 WHERE "__id" = 0;
UPDATE "alltypes" SET "o" = 42 WHERE "__id" = 0;
UPDATE "alltypes" SET "oulala" = 12345 WHERE "__id" = 0;
-- 2009-02-13 23:31:30 GMT
-- This is a comment. これは日本語です。
-- valid data
-- custom: toto_le_petit_rigolo
ALTER TABLE "alltypes" RENAME TO "all_types";
ALTER TABLE "all_types" RENAME COLUMN "s" TO "str";
CREATE TABLE "float"("__id" INTEGER PRIMARY KEY);
ALTER TABLE "float" ADD "value" REAL;
INSERT INTO "float"("__id") VALUES(0);
INSERT INTO "float"("__id") VALUES(1);
INSERT INTO "float"("__id") VALUES(2);
INSERT INTO "float"("__id") VALUES(3);
INSERT INTO "float"("__id") VALUES(4);
UPDATE "float" SET "value" = 0.1 WHERE "__id" = 0;
UPDATE "float" SET "value" = 0.2 WHERE "__id" = 1;
UPDATE "float" SET "value" = 0.3 WHERE "__id" = 2;
UPDATE "float" SET "value" = 0.4 WHERE "__id" = 3;
UPDATE "float" SET "value" = 0.5 WHERE "__id" = 4;
CREATE TABLE "toto"("__id" INTEGER PRIMARY KEY);
ALTER TABLE "toto" ADD "value" TEXT;
INSERT INTO "toto"("__id") VALUES(2);
INSERT INTO "toto"("__id") VALUES(4);
UPDATE "toto" SET "value" = X'746f746f' WHERE "__id" = 2;
INSERT INTO "float"("__id") VALUES(5);
INSERT INTO "float"("__id") VALUES(6);
INSERT INTO "float"("__id") VALUES(7);
INSERT INTO "float"("__id") VALUES(8);
INSERT INTO "float"("__id") VALUES(9);
INSERT INTO "float"("__id") VALUES(10);
INSERT INTO "float"("__id") VALUES(11);
INSERT INTO "float"("__id") VALUES(12);
INSERT INTO "float"("__id") VALUES(13);
INSERT INTO "float"("__id") VALUES(14);
INSERT INTO "float"("__id") VALUES(15);
INSERT INTO "float"("__id") VALUES(16);
INSERT INTO "float"("__id") VALUES(17);
INSERT INTO "float"("__id") VALUES(18);
INSERT INTO "float"("__id") VALUES(19);
INSERT INTO "float"("__id") VALUES(20);
INSERT INTO "float"("__id") VALUES(21);
INSERT INTO "float"("__id") VALUES(22);
INSERT INTO "float"("__id") VALUES(23);
INSERT INTO "float"("__id") VALUES(24);
DELETE FROM "float" WHERE "__id" = 19;
DELETE FROM "float" WHERE "__id" = 18;
DELETE FROM "float" WHERE "__id" = 17;
DELETE FROM "float" WHERE "__id" = 16;
DELETE FROM "float" WHERE "__id" = 15;
DELETE FROM "float" WHERE "__id" = 14;
DELETE FROM "float" WHERE "__id" = 13;
DELETE FROM "float" WHERE "__id" = 12;
DELETE FROM "float" WHERE "__id" = 11;
DELETE FROM "float" WHERE "__id" = 10;
COMMIT; --checkpoint = 610
COMMIT; --checkpoint = 610
