CREATE TABLE "city"("joedb_key" INTEGER PRIMARY KEY);
CREATE TABLE "person"("joedb_key" INTEGER PRIMARY KEY);
ALTER TABLE "city" ADD "name" TEXT;
ALTER TABLE "person" ADD "name" TEXT;
ALTER TABLE "person" ADD "city" INTEGER REFERENCES "city";
INSERT INTO "city"("joedb_key") VALUES(1);
UPDATE "city" SET "name" = X'5061726973' WHERE "joedb_key" = 1;
INSERT INTO "city"("joedb_key") VALUES(2);
UPDATE "city" SET "name" = X'4c696c6c65' WHERE "joedb_key" = 2;
INSERT INTO "person"("joedb_key") VALUES(1);
UPDATE "person" SET "name" = X'52c3a96d69' WHERE "joedb_key" = 1;
UPDATE "person" SET "city" = 2 WHERE "joedb_key" = 1;
INSERT INTO "person"("joedb_key") VALUES(2);
UPDATE "person" SET "name" = X'4e6f7262657274' WHERE "joedb_key" = 2;
UPDATE "person" SET "city" = 2 WHERE "joedb_key" = 2;
INSERT INTO "person"("joedb_key") VALUES(3);
UPDATE "person" SET "name" = X'416c6578616e647265' WHERE "joedb_key" = 3;
UPDATE "person" SET "city" = 1 WHERE "joedb_key" = 3;
DROP TABLE "city";
DROP TABLE "person";
CREATE TABLE "test"("joedb_key" INTEGER PRIMARY KEY);
ALTER TABLE "test" ADD "a" INTEGER;
ALTER TABLE "test" ADD "b" BIGINT;
INSERT INTO "test"("joedb_key") VALUES(1);
UPDATE "test" SET "a" = 1234 WHERE "joedb_key" = 1;
UPDATE "test" SET "b" = 5678 WHERE "joedb_key" = 1;
ALTER TABLE "test" ADD "d" TEXT;
ALTER TABLE "test" ADD "e" SMALLINT;
ALTER TABLE "test" DROP "a";
INSERT INTO "test"("joedb_key") VALUES(2);
UPDATE "test" SET "b" = 3 WHERE "joedb_key" = 2;
UPDATE "test" SET "d" = X'34' WHERE "joedb_key" = 2;
UPDATE "test" SET "e" = 0 WHERE "joedb_key" = 2;
DELETE FROM "test" WHERE "joedb_key" = 2;
UPDATE "test" SET "b" = 56789 WHERE "joedb_key" = 1;
CREATE TABLE "ref"("joedb_key" INTEGER PRIMARY KEY);
ALTER TABLE "ref" ADD "ref" INTEGER REFERENCES "test";
DROP TABLE "test";
DROP TABLE "ref";
CREATE TABLE "alltypes"("joedb_key" INTEGER PRIMARY KEY);
ALTER TABLE "alltypes" ADD "s" TEXT;
ALTER TABLE "alltypes" ADD "i32" INTEGER;
ALTER TABLE "alltypes" ADD "i64" BIGINT;
ALTER TABLE "alltypes" ADD "ref" INTEGER REFERENCES "alltypes";
ALTER TABLE "alltypes" ADD "b" SMALLINT;
ALTER TABLE "alltypes" ADD "f" REAL;
ALTER TABLE "alltypes" ADD "d" REAL;
ALTER TABLE "alltypes" ADD "o" SMALLINT;
ALTER TABLE "alltypes" ADD "oulala" SMALLINT;
INSERT INTO "alltypes"("joedb_key") VALUES(1);
UPDATE "alltypes" SET "s" = X'746f746f' WHERE "joedb_key" = 1;
UPDATE "alltypes" SET "i32" = 123456789 WHERE "joedb_key" = 1;
UPDATE "alltypes" SET "i64" = 123456789123456789 WHERE "joedb_key" = 1;
UPDATE "alltypes" SET "ref" = 1 WHERE "joedb_key" = 1;
UPDATE "alltypes" SET "b" = 1 WHERE "joedb_key" = 1;
UPDATE "alltypes" SET "f" = 3.14 WHERE "joedb_key" = 1;
UPDATE "alltypes" SET "d" = 3.14159 WHERE "joedb_key" = 1;
UPDATE "alltypes" SET "o" = 42 WHERE "joedb_key" = 1;
UPDATE "alltypes" SET "oulala" = 12345 WHERE "joedb_key" = 1;
-- timestamp 1234567890
-- "This is a comment. これは日本語です。"
-- custom: toto_le_petit_rigolo
ALTER TABLE "alltypes" RENAME TO "all_types";
ALTER TABLE "all_types" RENAME COLUMN "s" TO "str";
CREATE TABLE "float"("joedb_key" INTEGER PRIMARY KEY);
ALTER TABLE "float" ADD "value" REAL;
INSERT INTO "float"("joedb_key") VALUES(1);
INSERT INTO "float"("joedb_key") VALUES(2);
INSERT INTO "float"("joedb_key") VALUES(3);
INSERT INTO "float"("joedb_key") VALUES(4);
INSERT INTO "float"("joedb_key") VALUES(5);
UPDATE "float" SET "value" = 0.1 WHERE "joedb_key" = 1;
UPDATE "float" SET "value" = 0.2 WHERE "joedb_key" = 2;
UPDATE "float" SET "value" = 0.3 WHERE "joedb_key" = 3;
UPDATE "float" SET "value" = 0.4 WHERE "joedb_key" = 4;
UPDATE "float" SET "value" = 0.5 WHERE "joedb_key" = 5;
