// minimal set of files to be linked with a compiled database
#include "../Destructor_Logger.cpp"
#include "../Writable.cpp"
#include "../compiler/minimal_runtime_io.cpp"
#include "../journal/File.cpp"
#include "../journal/Generic_File.cpp"
#include "../journal/Memory_File.cpp"
#include "../journal/Readonly_Journal.cpp"
#include "../journal/Writable_Journal.cpp"
#include "../journal/SHA_256.cpp"
