#!/bin/bash
set -e

if [ "$1" == "" ]; then
 echo "Usage: $0 <file.joedb>"
 exit 1
fi

tmp_sqlite=$(mktemp /tmp/joedb_browser.XXXXXX)

joedb_push "$*" sql | sqlite3 "$tmp_sqlite"

sqlitebrowser "$tmp_sqlite"

rm "$tmp_sqlite"
