#!/bin/bash

if [ "$1" == "" ]; then
 echo "Usage: $0 <file.joedb>"
 exit 1
fi

editor=`which editor`

if [ ! -x "$editor" ]; then
 editor=`which vim`
fi

if [ ! -x "$editor" ]; then
 echo "Error: could not find an editor"
 exit 1
fi

tmp_joedb=$(mktemp /tmp/joedb_edit.XXXXXX.joedb)
tmp_joedbi="$tmp_joedb"i

echo tmp_joedbi=$tmp_joedbi

joedb_push "$1" dump >$tmp_joedbi || exit 1

while true; do
 echo running editor: $editor
 $editor $tmp_joedbi

 joedb_push interpreted $tmp_joedbi file $tmp_joedb
 if [ $? -ne 0 ]; then
  echo An error was detected. Press enter to go back into the editor.
  read
  continue
 fi

 joedb_push --check full $tmp_joedb file "$1"
 if [ $? -eq 0 ]; then
  echo Push was successful
 else
  echo Could not push changes. Press enter to overwrite the original file.
  read
  mv -v $1 $1.edit.$(date +%s).joedb || exit 1
  mv -vf $tmp_joedb "$1"
 fi

 break
done

rm -f $tmp_joedb $tmp_joedbi
