#!/bin/bash
set -e

if [ "$1" == "" ]; then
 echo "Usage: $0 <file.joedb>"
 exit 1
fi

tmp_sql=$(mktemp /tmp/joedb_browser.XXXXXX)
tmp_sqlite=$(mktemp /tmp/joedb_browser.XXXXXX)

{
 echo "BEGIN;"
 joedb_push "$*" sql || exit 1
 echo "COMMIT;"
} >"$tmp_sql"

sqlite3 "$tmp_sqlite" <"$tmp_sql"

sqlitebrowser "$tmp_sqlite"

rm "$tmp_sqlite" "$tmp_sql"
