name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: get gtest
      working-directory: ${{github.workspace}}/compcmake
      run: ./get_gtest.sh

    - name: install dependencies
      run: sudo apt-get -y install cmake ninja-build libssh-dev libboost-dev libboost-system-dev

    - name: Configure CMake
      working-directory: ${{github.workspace}}/compcmake
      run: ./generate.sh

    - name: Test
      working-directory: ${{github.workspace}}/compcmake/gcc_debug
      run: ctest -V
