name: Test on ubuntus

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
       sudo apt-get update
       sudo apt-get -y install cmake ninja-build libssh-dev clang clang-tidy gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf qemu-system-arm qemu-user libcurl4-openssl-dev

    - name: Configure CMake
      working-directory: ${{github.workspace}}/compcmake
      run: ./generate.sh

      # This does not work because somehow clang-11 is the default at github for Ubuntu 20,
      # and it does not match with clang-tidy's default version (still 10)
      #    - name: Test with clang in release mode
      #      working-directory: ${{github.workspace}}/compcmake/clang_release
      #      run: ctest -V

    - name: Test gcc_release
      working-directory: ${{github.workspace}}/compcmake/gcc_release
      run: ctest -V

    - name: Test cross-compiled ARM version
      working-directory: ${{github.workspace}}/compcmake/arm_release
      run: ctest -V

    - name: Test with gcc in asan mode
      working-directory: ${{github.workspace}}/compcmake/gcc_asan
      run: ctest -V

    - name: Test with gcc with joedb::File = joedb::Portable_File
      working-directory: ${{github.workspace}}/compcmake/gcc_portable
      run: ctest -V

    - name: deb packaging
      working-directory: ${{github.workspace}}/compcmake/gcc_release
      run: cpack -G DEB

    - name: deb install
      working-directory: ${{github.workspace}}/compcmake/gcc_release
      run: sudo apt-get --yes install ./joedb*.deb

    - name: about
      working-directory: /
      run: echo "about" | joedbi memory
