name: Test on ubuntus

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Install dependencies
      run: sudo apt-get -y install cmake ninja-build libssh-dev clang-tidy

    - name: Configure CMake
      working-directory: ${{github.workspace}}/compcmake
      run: ./generate.sh

    - name: Test with gcc in asan mode
      working-directory: ${{github.workspace}}/compcmake/gcc_asan
      run: ctest -V

    - name: Test with gcc with joedb::File = joedb::Portable_File
      working-directory: ${{github.workspace}}/compcmake/gcc_portable
      run: ctest -V

    - name: Test with clang in release mode
      working-directory: ${{github.workspace}}/compcmake/clang_release
      run: ctest -V

    - name: deb packaging
      working-directory: ${{github.workspace}}/compcmake/clang_release
      run: cpack -G DEB

    - name: deb install
      working-directory: ${{github.workspace}}/compcmake/clang_release
      run: sudo apt-get --yes install ./joedb*.deb

    - name: about
      working-directory: /
      run: echo "about" | joedbi
