name: Universal test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2019, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-14, macos-14-large, macos-13, macos-12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      working-directory: ${{github.workspace}}/compcmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      working-directory: ${{github.workspace}}/compcmake/build
      run: cmake --build .

    - name: Test in Windows
      working-directory: ${{github.workspace}}/test
      run: if [ "$RUNNER_OS" == "Windows" ]; then ../compcmake/build/Debug/joedb_test; else echo "Not Windows"; fi
      shell: bash

    - name: Test not in Windows
      working-directory: ${{github.workspace}}/compcmake/build
      run: if [ "$RUNNER_OS" != "Windows" ]; then ctest -V; else echo "Windows"; fi
      shell: bash
