name: Universal test

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2022, macos-10.15]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: git submodule init
      working-directory: ${{github.workspace}}
      run: git submodule init

    - name: git submodule update
      working-directory: ${{github.workspace}}
      run: git submodule update

    - name: Configure CMake
      working-directory: ${{github.workspace}}/compcmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/compcmake/build
      run: cmake --build .

    - name: Test
      working-directory: ${{github.workspace}}/test
      run: ../compcmake/build/$BUILD_TYPE/joedb_test
