name: Universal test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, macos-10.15]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: git submodule init
      working-directory: ${{github.workspace}}
      run: git submodule init

    - name: git submodule update
      working-directory: ${{github.workspace}}
      run: git submodule update

    - name: Configure CMake
      working-directory: ${{github.workspace}}/compcmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      working-directory: ${{github.workspace}}/compcmake/build
      run: cmake --build . --target joedb_test

    - name: Test in Windows
      working-directory: ${{github.workspace}}/test
      run: if [ "$RUNNER_OS" == "Windows" ]; then ../compcmake/build/Debug/joedb_test; else echo "Not Windows"; fi
      shell: bash

    - name: Test not in Windows
      working-directory: ${{github.workspace}}/compcmake/build
      run: if [ "$RUNNER_OS" != "Windows" ]; then ctest -V; else echo "Windows"; fi
      shell: bash
