name: Universal test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        #os: [windows-2022, windows-2019, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-14, macos-13, macos-12]
        config:
          - os: [macos-14]
            vcpkg_triplet: x64-osx-release
          - os: [ubuntu-22.04]
            vcpkg_triplet: x64-linux-release
          - os: [windows-2022]
            vcpkg_triplet: x64-windows-release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: vcpkg build
        id: vcpkg
        uses: johnwason/vcpkg-action@v6
        with:
          manifest-dir: ${{github.workspace}}/compcmake
          triplet: ${{matrix.config.vcpkg_triplet}}
          token: ${{github.token}}
          github-binarycache: true

      - name: Configure CMake
        working-directory: ${{github.workspace}}/compcmake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN8FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Test
        uses: threeal/ctest-action@v1.1.0
        with:
          test-dir: ${{github.workspace}}/compcmake/build
          verbose: true
          build-config: Debug
