name: Universal test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2019, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-15, macos-14, macos-13]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        working-directory: ${{github.workspace}}/compcmake
        shell: bash
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Test
        uses: threeal/ctest-action@v1.1.0
        with:
          test-dir: ${{github.workspace}}/compcmake/build
          verbose: true
          build-config: Debug
